/**:
  ros__parameters:
    min_longitudinal_offset: 0.2
    max_longitudinal_offset: 0.3
    min_lateral_offset: -0.25
    max_lateral_offset: 0.25
    min_height_offset: 0.5
    max_height_offset: 0.5
